CREATE TABLE movie (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Helps auto-generate IDs.
  year INT,
  title VARCHAR
);

CREATE TABLE rating (
  movie_id INT REFERENCES movie(id),
  viewer_id INT, -- There is no actual viewer table because all we have is an ID.
  rating INT,
  date_rated DATE
);
